name: sfa
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - anyio=3.5.0=py37h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h7f8727e_0
  - attrs=22.1.0=py37h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py37h06a4308_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cffi=1.15.1=py37h74dc2b5_0
  - curl=7.82.0=h7f8727e_0
  - debugpy=1.5.1=py37h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py37h06a4308_0
  - expat=2.4.9=h6a678d5_0
  - gdbm=1.18=hd4cb3f1_4
  - gettext=0.19.8.1=h9b4dc7a_1
  - git=2.34.1=pl5262hc120c5b_0
  - importlib-metadata=4.11.3=py37h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - ipykernel=6.15.2=py37h06a4308_0
  - ipython=7.31.1=py37h06a4308_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py37h06a4308_1
  - jsonschema=4.16.0=py37h06a4308_0
  - jupyter_client=7.3.5=py37h06a4308_0
  - jupyter_server=1.18.1=py37h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - krb5=1.19.2=hac12032_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libcurl=7.82.0=h0b77cf5_0
  - libedit=3.1.20210714=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.46.0=hce63b2e_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=py37h06a4308_0
  - mistune=0.8.4=py37h14c3975_1001
  - nbclassic=0.4.8=py37h06a4308_0
  - nbclient=0.5.13=py37h06a4308_0
  - nbconvert=6.4.4=py37h06a4308_0
  - nbformat=5.5.0=py37h06a4308_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.5=py37h06a4308_0
  - notebook=6.5.2=py37h06a4308_0
  - notebook-shim=0.2.2=py37h06a4308_0
  - openssl=1.1.1s=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.37=he7ceb23_1
  - perl=5.34.0=h5eee18b_2
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pkgutil-resolve-name=1.3.10=py37h06a4308_0
  - prometheus_client=0.14.1=py37h06a4308_0
  - psutil=5.9.0=py37h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pyparsing=3.0.9=py37h06a4308_0
  - pyrsistent=0.18.0=py37heee7806_0
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py37h06a4308_0
  - pyzmq=23.2.0=py37h6a678d5_0
  - readline=8.1=h27cfd23_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py37h06a4308_1
  - soupsieve=2.3.2.post1=py37h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - terminado=0.13.1=py37h06a4308_0
  - testpath=0.6.0=py37h06a4308_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.2=py37h5eee18b_0
  - traitlets=5.7.1=py37h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - websocket-client=0.58.0=py37h06a4308_4
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.0=py37h06a4308_0
  - pip
  - pip:
    - absl-py==1.4.0
    - addict==2.4.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - aliyun-python-sdk-core==2.13.36
    - aliyun-python-sdk-kms==2.16.1
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - backpack-for-pytorch==1.5.2
    - cachetools==5.3.0
    - chardet==3.0.4
    - charset-normalizer==2.0.12
    - click==8.1.3
    - colorama==0.4.6
    - contextlib2==21.6.0
    - cox==0.1.post3
    - crcmod==1.7
    - cryptography==41.0.1
    - cycler==0.11.0
    - cython==3.0.2
    - descartes==1.1.0
    - dill==0.3.7
    - docker-pycreds==0.4.0
    - einops==0.6.1
    - et-xmlfile==1.1.0
    - filelock==3.8.2
    - flatbuffers==23.5.26
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - ftfy==6.1.1
    - future==0.18.3
    - fvcore==0.1.5.post20221221
    - gast==0.4.0
    - gdown==4.7.1
    - geotorch==0.3.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.17.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.62.0
    - gputil==1.4.0
    - grad-cam==1.4.8
    - grpcio==1.54.0
    - h5py==3.7.0
    - huggingface-hub==0.16.4
    - hydra-core==1.3.2
    - idna==2.10
    - imageio==2.31.1
    - iopath==0.1.8
    - ipywidgets==8.0.6
    - jinja2==2.11.3
    - jmespath==0.10.0
    - joblib==1.2.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - jupyter==1.0.0
    - jupyter-console==6.6.3
    - jupyter-core==4.12.0
    - jupyterlab-widgets==3.0.7
    - keras==2.11.0
    - kiwisolver==1.4.4
    - libclang==16.0.6
    - lightning-utilities==0.9.0
    - littleutils==0.2.2
    - lmdb==1.4.1
    - markdown==3.4.3
    - markdown-it-py==2.2.0
    - markupsafe==2.1.5
    - matplotlib==3.5.3
    - mdurl==0.1.2
    - medpy==0.4.0
    - mizani==0.7.3
    - ml-collections==0.1.1
    - mmcls==0.25.0
    - mmcv-full==1.7.1
    - mmdet==3.0.0
    - mmengine==0.7.3
    - mock==5.1.0
    - model-index==0.1.11
    - multidict==6.0.4
    - munch==4.0.0
    - networkx==2.6.3
    - nose==1.3.7
    - numexpr==2.8.6
    - numpy==1.21.6
    - oauthlib==3.2.2
    - ogb==1.3.6
    - omegaconf==2.3.0
    - open-clip-torch==2.7.0
    - opencv-python==4.5.3.56
    - opendatalab==0.0.10
    - openmim==0.3.9
    - openpyxl==3.1.2
    - opt-einsum==3.3.0
    - ordered-set==4.1.0
    - oss2==2.17.0
    - palettable==3.3.3
    - pandas==1.1.5
    - pathtools==0.1.2
    - patsy==0.5.3
    - pillow==9.3.0
    - pip==24.0
    - plotnine==0.8.0
    - portalocker==2.7.0
    - pretrainedmodels==0.7.4
    - prettytable==3.7.0
    - promise==2.3
    - prompt-toolkit==3.0.38
    - protobuf==3.19.6
    - py3nvml==0.2.7
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycocotools==2.0.6
    - pycryptodome==3.18.0
    - pydeprecate==0.3.1
    - pygments==2.15.1
    - pyopenssl==23.2.0
    - pysocks==1.7.1
    - pytz==2023.3
    - pywavelets==1.3.0
    - pyyaml==6.0
    - qtconsole==5.4.3
    - qtpy==2.3.1
    - randaugment==1.0.2
    - regex==2022.10.31
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rich==13.3.5
    - robustness==1.2.1.post2
    - rsa==4.9
    - ruamel-yaml==0.18.5
    - ruamel-yaml-clib==0.2.8
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.1
    - sconf==0.2.5
    - seaborn==0.12.2
    - sentencepiece==0.1.99
    - sentry-sdk==1.9.0
    - setproctitle==1.3.2
    - shapely==2.0.1
    - simpleitk==2.3.0
    - simplejson==3.19.2
    - smmap==5.0.0
    - statsmodels==0.13.5
    - tables==3.7.0
    - tabulate==0.9.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6
    - termcolor==2.3.0
    - terminaltables==3.1.10
    - tfds-nightly==4.4.0.dev202201080107
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - timm==0.6.13
    - tomli==2.0.1
    - torch==1.13.0
    - torchdiffeq==0.2.3
    - torchmetrics==0.11.4
    - torchvision==0.14.0
    - tqdm==4.65.0
    - ttach==0.0.3
    - typeguard==4.1.2
    - typing-extensions==4.7.1
    - urllib3==1.25.11
    - visdom==0.2.3
    - wandb==0.15.5
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.7
    - wilds==2.0.0
    - wrapt==1.16.0
    - xlrd==1.2.0
    - xmltodict==0.13.0
    - yacs==0.1.8
    - yapf==0.33.0
    - yarl==1.9.2
prefix: /home/ts/anaconda3/envs/sfa
